In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [3]:
hello = tf.constant('Hello world', name = 'hello')

In [4]:
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world'>

In [5]:
hello_2 = tf.constant('Hello', shape = [5,2], name = 'hello')

In [6]:
hello_2

<tf.Tensor: shape=(5, 2), dtype=string, numpy=
array([[b'Hello', b'Hello'],
       [b'Hello', b'Hello'],
       [b'Hello', b'Hello'],
       [b'Hello', b'Hello'],
       [b'Hello', b'Hello']], dtype=object)>

In [7]:
print(hello_2)

tf.Tensor(
[[b'Hello' b'Hello']
 [b'Hello' b'Hello']
 [b'Hello' b'Hello']
 [b'Hello' b'Hello']
 [b'Hello' b'Hello']], shape=(5, 2), dtype=string)


In [8]:
tf.compat.v1.reset_default_graph()

In [9]:
from tensorflow.python.keras.datasets import boston_housing

#load data
(features, actual_price), _ = boston_housing.load_data(test_split = 0)

In [10]:
features.shape

(506, 13)

In [11]:
print(type(features))

<class 'numpy.ndarray'>


In [12]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

features = sc.fit_transform(features)

In [13]:
features[0]

array([-0.2770909 , -0.48772236, -0.43725801, -0.27259857, -0.14421743,
       -0.20320532,  0.82234174,  0.08644935, -0.6379618 , -0.6012761 ,
        1.17646583,  0.44105193,  0.85042548])

In [14]:
actual_price.shape[0]

506

**Building the Computational Graph**

In [15]:
tf.compat.v1.disable_eager_execution() 

x = tf.compat.v1.placeholder(shape = [None, 13], dtype = tf.float32, name = 'x_input')

y = tf.compat.v1.placeholder(shape = [None], dtype = tf.float32, name = 'y_input')

In [16]:
W = tf.Variable(tf.zeros(shape = [13, 1]), name = 'weights')

b = tf.Variable(tf.zeros(shape = [1]), name = 'bias')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [17]:
y_hat = tf.add(tf.matmul(x, W), b, name = 'predicted_output')

In [18]:
loss = tf.reduce_mean(tf.square(y_hat - y), name = 'Loss')

In [19]:
train_op = tf.compat.v1.train.GradientDescentOptimizer(0.03).minimize(loss) # 0.03 is the learning rate

**Executing the Computational Graph**

In [20]:
sess = tf.compat.v1.Session()

sess.run(tf.compat.v1.global_variables_initializer())

training_epochs = 100

In [21]:
for epoch in range(training_epochs):
   _, training_loss = sess.run([train_op, loss], feed_dict = {x : features, y : actual_price})

   if epoch % 10 == 0:
     print("Epoch : {0}, cost : {1}".format(epoch, training_loss))

Epoch : 0, cost : 592.14697265625
Epoch : 10, cost : 231.71432495117188
Epoch : 20, cost : 127.15068054199219
Epoch : 30, cost : 96.81608581542969
Epoch : 40, cost : 88.01585388183594
Epoch : 50, cost : 85.46292114257812
Epoch : 60, cost : 84.72219848632812
Epoch : 70, cost : 84.50736236572266
Epoch : 80, cost : 84.4450454711914
Epoch : 90, cost : 84.42697143554688


In [22]:
features[0]

array([-0.2770909 , -0.48772236, -0.43725801, -0.27259857, -0.14421743,
       -0.20320532,  0.82234174,  0.08644935, -0.6379618 , -0.6012761 ,
        1.17646583,  0.44105193,  0.85042548])

In [23]:
sess.close()